print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")