print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Let's create a conflict")
print("Hello iNeuron!!")
print("Hell0")
print("Hello iNeuron!!")
print("Hell0")
